### ISSUE TITLE
Sort Bags With Quiver

### ISSUE THREAD

**Issue by EnsignPayton** [ElvUI-Vanilla/ElvUI#22]
Sort bags feature fails if a quiver / ammo pouch / etc. is equipped

**Comment by Crumdidlyumshis** [comment]
Oh yeah, something I forgot about. I believe it has to do with this shitty function I wrote: https://github.com/ElvUI-Vanilla/ElvUI/blob/auras-work/ElvUI/Modules/Bags/Sort.lua#L372

**Comment by Crumdidlyumshis** [comment]
Actually, it works (not fully). If the ammo or quiver bag is placed at the end of the bags, it sorts correctly. Something to do with the order and bag type.
