### ISSUE TITLE
chinese Client classTextColor error

### ISSUE THREAD

**Issue by Qcat0214** [ElvUI-Vanilla/ElvUI#26]
in FriendsFrame. Unable to display the correct  class colors and class icons
Message: ...face\AddOns\ElvUI\Modules\Skins\Blizzard\Friends.lua:272: attempt to index global `classTextColor' (a nil value)
Time: 06/09/18 23:17:18
Count: 1
Stack: ...face\AddOns\ElvUI\Modules\Skins\Blizzard\Friends.lua:272: in function <...face\AddOns\ElvUI\Modules\Skins\Blizzard\Friends.lua:256>
Interface\AddOns\!Compatibility\api\wowAPI.lua:111: in function `GuildStatus_Update'
Interface\FrameXML\FriendsFrame.lua:117: in function `FriendsFrame_Update'
Interface\FrameXML\FriendsFrame.lua:73: in function `FriendsFrame_OnShow'
[string "FriendsFrameTab3:OnClick"]:3: in main chunk

**Comment by Qcat0214** [comment]
<img src='http://i4.fuimg.com/609861/95ca49f78b9eddd1.png'>
<img src='http://i4.fuimg.com/609861/2acccd6941a94a6a.png'>

**Comment by Bunny67** [comment]
check after last update
