### ISSUE TITLE
ElvUI for 1.12 conflicts with addon called pfQuest

### ISSUE THREAD

**Issue by jallstein** [ElvUI-Vanilla/ElvUI#30]
Issue: Action bar module of ElvUI throws errors while addon pfQuest is enabled.

This is the error message: https://pastebin.com/8WRHUG1t
This is the conflicting addon: http://shagu.org/pfQuest/

Both ElvUI and pfQuest are the latest version as of the time of writing, ElvUI received updates less than 30 minutes ago.

**Comment by Crumdidlyumshis** [comment]
Still having the issue?

**Comment by jallstein** [comment]
The issue seems to be resolved! Well done.
