### ISSUE TITLE
ElvUI causes client to stutter after disabling action bar module

### ISSUE THREAD

**Issue by jallstein** [ElvUI-Vanilla/ElvUI#31]
Issue: Disabling ElvUI's action bar module in the settings causes the client to stutter when repeatedly casting buffs.

Repro steps:
Log in, perform first time setup.
Ensure scrolling combat text is enabled in options.
Disable action bar module in ElvUI settings, reload UI when prompted.
Repeatedly apply buffs to self.

Expected outcome: Client should noticeably stutter every time a buff is cast.
Issue persists through client restarts.

System details: Client is enGB locale.
Norwegian language keyboard layout, most recent Windows 10 update installed. Client is not running in compatibility mode and is not being run with administrator privileges.

Client framerate is manually capped to 128 via external tool.
Display refresh rate set to 120hz in the game's video settings (upper limit, engine can't go higher).
Client running in borderless windowed mode.
Windows shows 144hz display refresh rate. This is what the display is actually running at.

**Comment by Crumdidlyumshis** [comment]
cannot reproduce
