### ISSUE TITLE
Atlasloot Enhanced conflicts with ElvUI vanilla when trying to access ElvUI options menu

### ISSUE THREAD

**Issue by jallstein** [ElvUI-Vanilla/ElvUI#32]
Error message:

Message: ...ies\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:547: bad argument #1 to `?' (table contains non-strings)
Time: 06/23/18 05:50:00
Count: 1
Stack: [C]: ?
...ies\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:547: in function `Select'
...ies\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:559: in function `SelectByValue'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1689: in function `FeedGroup'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1871: in function `?'
Interface\AddOns\ElvUI\Init.lua:149: in function `ToggleConfig'
Interface\AddOns\ElvUI\Init.lua:82: in function <Interface\AddOns\ElvUI\Init.lua:81>

That is an exact copy/paste from the error frame.

The addon in question may be found here: https://github.com/Cabro/Atlas

**Comment by Crumdidlyumshis** [comment]
I just updated it, however, this does not fix your error, but it does allow both versions of the addon to be skinned. Also, please note, for now it is best to use the original Atlas of version 1.8.1 to eliminate any LUA errors for now.
