### ISSUE TITLE
Raid/Party Frames

### ISSUE THREAD

**Issue by kevinmd88** [ElvUI-Vanilla/ElvUI#33]
Having a strange problem where I join a group and ElvUI shows both the party and raid frames regardless of what kind of group I'm in.

I checked the visibility macro for each:

Raid Frames:
[@raid6,noexists] hide;show

Party Frames:
[@raid6,exists][nogroup] hide;show

Beyond that I have no idea what to try.

**Comment by Crumdidlyumshis** [comment]
Yeah the unit frames need some more work done to them. @Bunny67 will work on unitframes more when he gets a chance. I will do what I can on them but he understands them a bit more than me.

**Comment by Crumdidlyumshis** [comment]
Try the latest
