### ISSUE TITLE
UI Scaling Issue

### ISSUE THREAD

**Issue by Maratain2004** [ElvUI-Vanilla/ElvUI#43]
If you set the UI scale to the lowest in the video options, this causes several problems, firstly in the 'Anchor' section, the grid only covers that of which it would if the UI scale was set to the default. This means you cannot drag components to the bottom sides of the screen.

As well as this, the borders of several UI elements such as the character panel and the bag only half show with the UI scale set this low. 

Cause: Unknown, possible vanilla limitation issue (according to Shagu, same issue persists with his PFUI)

**Comment by Crumdidlyumshis** [comment]
Try latest
