### ISSUE TITLE
LuaError

### ISSUE THREAD

**Issue by madmaxo88** [ElvUI-Vanilla/ElvUI#46]
Message: Interface\AddOns\ElvUI\Libraries\oUF\colors.lua:96: attempt to perform arithmetic on local `r2' (a nil value)
Time: 07/22/18 12:53:41
Count: 1423
Stack: [C]: ?
Interface\AddOns\ElvUI\Libraries\oUF\colors.lua:96: in function <Interface\AddOns\ElvUI\Libraries\oUF\colors.lua:93>
(tail call): ?
Interface\AddOns\ElvUI\Modules\UnitFrames\Tags.lua:49: in function `?'
...terface\AddOns\ElvUI\Libraries\oUF\elements\tags.lua:725: in function `UpdateTag'
...terface\AddOns\ElvUI\Libraries\oUF\elements\tags.lua:475: in function <...terface\AddOns\ElvUI\Libraries\oUF\elements\tags.lua:470>

**Comment by Bunny67** [comment]
how to reproduce?

**Comment by Bunny67** [comment]
Check now

**Comment by Loaal** [comment]
fixed 4557a15bcf96047417122f06704abce812b8dbd0
