### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by madmaxo88** [ElvUI-Vanilla/ElvUI#47]
Message: Interface\AddOns\ElvUI\Core\toolkit.lua:193: CreateFrame: Couldn't find 'this' in parent object
Time: 07/22/18 15:04:21
Count: 1
Stack: (tail call): ?
[C]: in function `CreateFrame'
Interface\AddOns\ElvUI\Core\toolkit.lua:193: in function `CreateBackdrop'
Interface\AddOns\ElvUI\Modules\Skins\Skins.lua:249: in function `HandleEditBox'
...terface\AddOns\ElvUI\Modules\Skins\Blizzard\Mail.lua:140: in function <...terface\AddOns\ElvUI\Modules\Skins\Blizzard\Mail.lua:19>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: in function `xpcall'
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\ElvUI\Modules\Skins\Skins.lua:585: in function `Initialize'
Interface\AddOns\ElvUI\Modules\Skins\Skins.lua:611: in function <Interface\AddOns\ElvUI\Modules\Skins\Skins.lua:610>
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:155: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
...
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\ElvUI\Core\core.lua:998: in function `InitializeModules'
Interface\AddOns\ElvUI\Core\core.lua:1106: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: in function `xpcall'
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Quaxxon** [comment]
I have the exact same issue. appears when logging in

**Comment by Crumdidlyumshis** [comment]
I got all screwed up on the # of the issue. I think I had cache issues or something.
