### ISSUE TITLE
Several issues.

### ISSUE THREAD

**Issue by devellio** [ElvUI-Vanilla/ElvUI#48]
**Description**
A few issues with only brief usage. I'm sure there's more to be found.

1.  Having Atlas Quest/Loot causes elvui configuration window not to open. There are several other addons that cause this issue as well.
2. Drop-downs seem to duplicate themselves upon each click until it's a long, scrollable list of duplicate options for both font and texture drop-downs.
3. Cannot right click on unit frames. Self, target, party, targetoftarget tested - nothing happens on right click. Such as right clicking on self to leave party. This is the only one I'd consider major.
4. No options for buffs/debuffs on target unitframe and it shows them by default.

**Version Number**
0.50 - (last commit: 83f43bd)

**Only ElvUI Enabled**
Yes, these issues occur when only ElvUI is enabled.

**Blizzard Issue?**
These issues are specific to ElvUI only.

**Comment by devellio** [comment]
More issues observed.

5. Can't click on item links in chat. Tooltip does show item info, though.
6. Can't shift click names to do a who to get character info.
7. Can't have chat input open and shift click a name to have name put into input box.
8. Names aren't colored by class in chat. Even after doing /who, /rl, etc.
9. There doesn't appear to be a target castbar option under unitframe options. This may be a vanilla thing, but I know pfui can do it, and there are options for this under Nameplates - not sure if those work yet.

**Comment by Crumdidlyumshis** [comment]
@devellio We appreciate your feedback! However, it is harder for us to keep track of whats been fixed and what hasn't when we have an issue filled with multiple issues. It is best to create individual issues. I know this may be inconvenient for you, but it helps us. If you don't mind, please create separate issues. Thanks!

**Comment by devellio** [comment]
Sure, I understand. If you want to close this, I'll submit individual issue reports for each issue I come across. It's been a bit odd. Last night many of the issues I'd been experiencing had somehow starting working correctly later into the night. It's hard to track, but I appreciate your guys' work on backporting this to 1.1.2.1.

**Comment by Crumdidlyumshis** [comment]
Thank you for your support and feedback!
