### ISSUE TITLE
[Request] Show Combo Points and "Energy Watch"

### ISSUE THREAD

**Issue by ProtonKnight** [ElvUI-Vanilla/ElvUI#56]
**Description**
please provide a way to track combo points on target and energy tick

**Comment by Zhaile** [comment]
I see this has been edited, but I don't see any replies. I found the "Combobar" panel under Unitframes -> Target Frame, and I thought this was the combo point tracker. Unfortunately, even when detaching it from the frame, there's nothing to see. As I don't see a description for what the "information panel" is for, I thought maybe this was needed to be enabled to show the combo points.

Given how critical combo points are for rogues and druids, can we please get an answer on if this is being worked on?

P.s. Much love for making this. it's the ONE thing I knew I'd miss going back to Vanilla.
