### ISSUE TITLE
Quest Reward

### ISSUE THREAD

**Issue by datka1** [ElvUI-Vanilla/ElvUI#62]
Quest Reward cannot be selected. After /reload seems to work. Then Brokes again

**Comment by Crumdidlyumshis** [comment]
Need more details like whats addons you used, what quest, any errors, etc...
I have not encountered this yet.

**Comment by datka1** [comment]
Ok. Little Update. as i noticed not only quest reward selection doesnot works. also in quest log quest selection doesnot work. and sometimes target frames hp or backround extends and blinks in like 10 times in  1 second. i can see Click animation but its not switching in quest log. And when you move any frame and click on X and Y boxes it gets an error.

**Comment by Crumdidlyumshis** [comment]
Okay now I see what your talking about. There appears to be an issue when loading The ElvUI config. For now after changing any settings you can do a /rl or /reload and those things should work. If you open the config again it will repeat the same issue. 

I will look into it and hopefully find a fix. This will take some time debugging.
