### ISSUE TITLE
When I user ElvUI_AddOnSkins and AtlasQuest, there is an error

### ISSUE THREAD

**Issue by magical2019** [ElvUI-Vanilla/ElvUI#71]
**Description**
When use Atlas, AtlasLoot, AtlasQuest, ElvUI_AddOnSkins, but atlasQuest skin report an error.
Only use Atlas, AtlasLoot, AtlasQuest, there is no error.

**Version Number**
0.85

**Steps to Reproduce**
enter the game or reload

**Expected Behavior**

**Actual Behavior**

**Only ElvUI Enabled**

**Blizzard Issue?**

**Additional Information**

**Error Log**
Message: Interface\AddOns\ElvUI\Core\toolkit.lua:241: attempt to index local `object' (a nil value)
Time: 12/07/18 09:36:04
Count: 1
Stack: (tail call): ?
Interface\AddOns\ElvUI\Core\toolkit.lua:241: in function `StripTextures'
...\AddOns\ElvUI_AddOnSkins\Skins\Addons\atlasQuest.lua:57: in function <...\AddOns\ElvUI_AddOnSkins\Skins\Addons\atlasQuest.lua:6>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: in function `xpcall'
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\ElvUI\Modules\Skins\Skins.lua:577: in function `Initialize'
Interface\AddOns\ElvUI\Modules\Skins\Skins.lua:611: in function <Interface\AddOns\ElvUI\Modules\Skins\Skins.lua:610>
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:155: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:155>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: in function `xpcall'
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
Interface\AddOns\ElvUI\Core\core.lua:1027: in function `InitializeModules'
Interface\AddOns\ElvUI\Core\core.lua:1141: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: in function `xpcall'
[string "safecall Dispatcher[1]"]:13: in function `?'
...ibraries\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Crumdidlyumshis** [comment]
What version of AtlasQuest are you using?

The one skinned if for AtlasQuest v4.1.3
