### ISSUE TITLE
AtlasLoot causes the team frame to not display

### ISSUE THREAD

**Issue by magical2019** [ElvUI-Vanilla/ElvUI#74]
**Description**
AtlasLoot Version: 4.06.06
download form https://github.com/Cabro/Atlas
team frame not display

**Version Number**
Version: 0.85

**Steps to Reproduce**
Invite friends to enter the team without displaying the team frame

**Expected Behavior**
Display team frame

**Actual Behavior**
not display team frame

**Only ElvUI Enabled**
only elvui and AtlasLoot, When i open elvui settings there is a lua error below. When i use a !Libs addons, the error has disappeared, but still not showing the team frame.
Message: ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1843: AceConfigRegistry-3.0:ValidateOptionsTable(): ElvUI.args.nameplate.args.enemyPlayerGroup.args.nameGroup.name: expected a string or funcref, got 'table: 2410D6A8'
Time: 12/07/18 19:19:50
Count: 1
Stack: [C]: ?
[C]: in function `error'
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:50: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:45>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:189: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:184>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:223: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:198>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:233: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:198>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:233: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:198>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:233: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:198>
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:261: in function `ValidateOptionsTable'
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:303: in function `app'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1843: in function `?'
Interface\AddOns\ElvUI\Init.lua:222: in function `ToggleConfig'
Interface\AddOns\ElvUI\Init.lua:110: in function <Interface\AddOns\ElvUI\Init.lua:109>

**Blizzard Issue?**

**Additional Information**

**Error Log**

```

```

**Comment by Crumdidlyumshis** [comment]
Please use either AtlasLoot 1.18.02 and AtlasLoot 4.07.01 (TBC Backport)

https://github.com/ElvUI-Vanilla/ElvUI_AddOnSkins/blob/master/ElvUI_AddOnSkins/Skins/Addons/atlasLoot.lua#L4

Download for [4.07.01](https://github.com/Hosq/Atlas)

**Comment by magical2019** [comment]
Thank you!
