### ISSUE TITLE
Buffs Disappear

### ISSUE THREAD

**Issue by EnsignPayton** [ElvUI-Vanilla/ElvUI#9]
Sometimes buffs will fail to display while still being active on the player. They usually return a short time later. It seems random, I haven't pinned down an event that's triggering the behavior

**Comment by Crumdidlyumshis** [comment]
Just to make sure, your using /etrace to show events?

**Comment by EnsignPayton** [comment]
I didn't know that existed, I'll try it

**Comment by Crumdidlyumshis** [comment]
I have noticed this before on my hunter with an aspect of cheetah on. I think it could be related to a PLAYER_ENTERING_WORLD or PLAYER_LOGIN. I’ll look into it when I can.

**Comment by Crumdidlyumshis** [comment]
I haven't noticed this recurring in a while, closing for now, reopen if needed.
